### ISSUE TITLE
Merge the apps

### ISSUE THREAD

**Issue by justinxreese** [saxifrage/learn#105]
How to build angular apps on heroku: 

http://www.angularonrails.com/deploy-angular-rails-single-page-application-heroku/

**Comment by justinxreese** [comment]
Going to rely largely on @MatthewVita to put the app in place in the `client` directory and then I will work with him to configure heroku to build the app at deploy time

**Comment by MatthewVita** [comment]
@justinxreese thanks for the link. The article's app uses Grunt, but we're using Gulp. Probably a non-issue, however.

I'll be playing around with this in the coming days.

**Comment by MatthewVita** [comment]
@justinxreese so far  I've just followed that article in terms of throwing the `build/` folder (generated by gulp of the client) in the `public` directory and it seems to load up everything correctly, however, RoR is complaining a bit:

is it the case that we simply need a catch-all static asset route?

```
=> Booting Puma
=> Rails 4.2.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.11.1 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:3000




Started GET "/%7B%7Bo.img%7D%7D" for 127.0.0.1 at 2015-05-05 22:49:43 -0400
Started GET "/%7B%7Bo.img%7D%7D" for 127.0.0.1 at 2015-05-05 22:49:43 -0400
  [1m[36mActiveRecord::SchemaMigration Load (0.3ms)[0m  [1mSELECT "schema_migrations".* FROM "schema_migrations"[0m
  [1m[36mActiveRecord::SchemaMigration Load (0.3ms)[0m  [1mSELECT "schema_migrations".* FROM "schema_migrations"[0m

ActionController::RoutingError (No route matches [GET] "/%7B%7Bo.img%7D%7D"):
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:22:in `middleware_call'
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  puma (2.11.1) lib/puma/server.rb:507:in `handle_request'
  puma (2.11.1) lib/puma/server.rb:375:in `process_client'
  puma (2.11.1) lib/puma/server.rb:262:in `block in run'
  puma (2.11.1) lib/puma/thread_pool.rb:104:in `call'
  puma (2.11.1) lib/puma/thread_pool.rb:104:in `block in spawn_thread'



ActionController::RoutingError (No route matches [GET] "/%7B%7Bo.img%7D%7D"):
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:22:in `middleware_call'
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  puma (2.11.1) lib/puma/server.rb:507:in `handle_request'
  puma (2.11.1) lib/puma/server.rb:375:in `process_client'
  puma (2.11.1) lib/puma/server.rb:262:in `block in run'
  puma (2.11.1) lib/puma/thread_pool.rb:104:in `call'
  puma (2.11.1) lib/puma/thread_pool.rb:104:in `block in spawn_thread'


  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_trace.html.erb (1.0ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_trace.html.erb (1.0ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.0.0/lib/action_dispatch/templates/routes/_route.html.erb (2.1ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.0.0/lib/action_dispatch/templates/routes/_route.html.erb (2.1ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.0.0/lib/action_dispatch/templates/routes/_table.html.erb (4.9ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.0.0/lib/action_dispatch/templates/routes/_table.html.erb (4.9ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_request_and_response.html.erb (8.9ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_request_and_response.html.erb (8.9ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_web_console.html.erb (1.4ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_web_console.html.erb (1.4ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/routing_error.html.erb within rescues/layout (44.1ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/routing_error.html.erb within rescues/layout (44.1ms)
Exiting
```

**Comment by justinxreese** [comment]
Not a route, but a configuration to serve static assets. Will take a look
tomorrow

**Comment by MatthewVita** [comment]
Hey @justinxreese how's it going on this configuration stuff? Need a hand?

**Comment by justinxreese** [comment]
@MatthewVita I need your changes. Are they on a branch anywhere?

**Comment by MatthewVita** [comment]
@justinxreese here you go: https://github.com/saxifrage/learn/tree/client

...this will be a good start. Obviously we have a bunch of work to go to truely merge them.

`cd` into `client`, run `npm i`, then run `gulp`... you should see everything show up in `public`

**Comment by timothyfcook** [comment]
Thanks @MatthewVita ...Onward!

**Comment by justinxreese** [comment]
@MatthewVita I'm not seeing the errors your referring to with the way it is configured right now. What steps are you taking to see that? It's working as-is as far as I can tell. I just visit `http://localhost:3000/` and see the angular built app

**Comment by justinxreese** [comment]
Nevermind. I see it. Was confused. 
![](http://i.imgur.com/zV6UknP.jpg)

I think you're just linking to something wrong in the code and there is legitimately not a file there. Everything else works pretty well.

**Comment by justinxreese** [comment]
I think this issue is good to close, unless we want to include me configuring our deployment to build the app?

**Comment by MatthewVita** [comment]
we'll do the deploy stuff later, but that should be another issue anyways
